[package]
name = "nix-incognito-test"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = { version = "1.12.0", features = ["attributes"]}
colored = "2.1.0"
zbus = "4.1.2"
